services:
  nuxt-ts-tailwind:
    build:
      context: ./nuxt-ts-tailwind
      dockerfile: ./docker/dockerfile-stage
    container_name: nuxt-ts-tailwind
    ports:
      - 3000:3000
    env_file:
      - ./env/.env.stage