# Generated by Django 4.2.7 on 2024-07-11 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_uuid', models.UUIDField(editable=False, null=True)),
                ('datetime', models.DateTimeField()),
                ('label', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
