# Generated by Django 4.2.7 on 2024-07-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customuser_groups_delete_customgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
