# Generated by Django 4.2.7 on 2024-07-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
