# Generated by Django 4.2.7 on 2024-07-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
