FROM node:20.7.0-slim

WORKDIR /app

COPY . .

RUN npm ci

CMD [ "npm", "run", "dev" ]

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000

# RUN node run build
# CMD [ "node", "./build/index.js" ]
# CMD ["node", ".output/server/index.mjs"]